#!/bin/sh

# system
if [ -f /etc/os-release ]; then
    OS=$(grep "^PRETTY_NAME=" /etc/os-release | cut -d= -f2 | tr -d '"')
else
    OS="Unknown"
fi

ARCH=$(uname -m)
KERNEL=$(uname -r)

WM=$(echo "$XDG_CURRENT_DESKTOP")
[ -z "$WM" ] && WM="Unknown"

SHELL=$(basename "$SHELL")
RAMUSAGE=$(free -m | awk '/Mem:/ {print $3 "/" $2 "M"}')

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

printf "    .--.      ${BLUE}%s${NC}@%s\n" "$(whoami)" "$(hostname)"
printf "   |o_o |     ---------------------\n"
printf "   |:_/ |     ${BLUE} ⸳ ${NC}%s %s\n" "$OS" "$ARCH"
printf "  //   \\ \\    ${RED} ⸳ ${NC}%s\n" "$KERNEL"
printf " (|     | )   ${YELLOW} ⸳ ${NC}%s\n" "$WM"
printf "/'\\_   _/'\\   ${GREEN} ⸳ ${NC}%s\n" "$SHELL"
printf "\\___)=(___/   ${PURPLE} ⸳ ${NC}%s\n" "$RAMUSAGE"
